### ISSUE TITLE
Ds_Merchant_MerchantURL not executed

### ISSUE THREAD

**Issue by psp589** [mbuenoferrer/RedsysTPV#1]
Hello, first of all thanks for you work it's been really helpfull.
I'm running your RedsysTPV.WebSample and everything seems to work fine with the payment, but the ResponseController is never called , it is supposed to be called when the payment is ok isnt it? because of we set it  in the  Ds_Merchant_MerchantURL parameter on the request.

after putting the CIP code on the page I get a message "operacion autorizada con codigo.." with a green background , and then when I press "CONTINUAR" I go to the ResponseController.

Do you know if i'm doing anything wrong or what's happening?

Thank you.

**Comment by mabuenox** [comment]
Hi Pablo

Yes, the flow is like you're describing. The value of "Ds_Merchant_MerchantURL" is the url that Redsys will call asynchronously always when payment is finished (either is success or not). Note that this page never will be call or redirect from a browser; only the servers of Redsys will call it and persists the response status on their systems (usually take the HTTP code 200 or 500, and you could see on the Redsys private area)

How you know Redsys is not calling to your url? Maybe are you running the web on localhost, which is unreachable for Redsys servers?

**Comment by psp589** [comment]
Yes, you're right I found out latter that the reason is that I was running it on localhost, thanks!

**Comment by osatxi** [comment]
Hola, 

Lo primero muchísimas gracias por el código. Aunque tengo el mismo problema no consigo obtener la respuesta de la petición, me podéis indicar que tengo hacer. No estoy ejecutando la web en localhost, pero sigo sin obtener el resultado para tratarlo. 

Gracias de antemano.

Un saludo.

**Comment by psp589** [comment]
¿El sitio web es accesible desde el exterior? Para que Redsys  te pueda enviar la respuesta tienes que tener IP y Puerto públicos abiertos

**Comment by DbNero16** [comment]
Buenos días,,

Tengo el mismo problema que se ha comentado en este post; en primera instancia pensé que el problema sería el recurrente aquí descrito, el estar ejecutando en localhost. Sin embargo, pasé a publicar el sitio con una ip pública, teniendo acceso público, para comprobar si era esta la razón.

Pese a esto, parece que se sigue sin llamar a dicha URL; inserté un log en el que se escribe sobre la base de datos y la acción correspondiente a esa URL no se ejecuta. Sin embargo, la acción correspondiente a la URLOK, si que se lanza. He pensado que tal vez la razón sea que redsys de primeras no esté configurado para enviar notificaciones, pero al ser desarrollador no he encontrado la manera de realizar una supuesta configuración del sitio para probar esto.

¿Sabéis alguna posible razón para que esto suceda?

Gracias y un saludo.

**Comment by mabuenox** [comment]
Es difícil saber cuál es el problema sin conocer la infraestructura de red en la que se está ejecutando, pero es muy probable que tenga que ver con la conectividad del servidor.

Redsys ofrece un panel de gestión para realizar diversas consultas. En el mismo hay una sección de "Notificaciones", donde se guarda un log de lo que ha intentado comunicar y su resultado. Mira a ver que pone aquí, es una fuente de información más fiable que un log propio.

Como se puede ver en la captura, vienen los detalles de la url a la que realiza la notificación, y su resultado (código 200 significa que ha sido correcto).

![image](https://user-images.githubusercontent.com/2506499/38980368-f4013e1e-43bc-11e8-93dc-7f3634f50b20.png)

Saludos.

**Comment by DbNero16** [comment]
Buenos días y muchas gracias por su respuesta,

A día de hoy, esto se está realizando bajo un entorno de pruebas con los datos ofrecidos por Redsys en cuanto a número de comercio, terminales etc, dado que la implementación se realiza de cara a llevarse a cabo en terceras empresas. Por lo que entiendo, para acceder a ese panel, debería acceder haciendo uso de los datos de un comercio concreto, ¿me equivoco? Porque no tengo unos datos "reales", para poder interactuar con ellos..

Gracias y un saludo.

**Comment by mabuenox** [comment]
Efectivamente, si Redsys te ha asignado un número de comercio de prueba, también tiene que proporcionarte la información para acceder a ese panel.

En el entorno de pruebas, el acceso al módulo de administración es en la url https://sis-t.redsys.es:25443/canales/, donde podrías ver todo lo referente a notificaciones, pero obviamente necesitas usuario y contraseña. No debería haber ningún problema en que el soporte de Redsys te lo proporcione.

Saludos.

**Comment by DbNero16** [comment]
Perfecto, me pondré en contacto con ellos, a ver si a través de ese panel damos con la solución.

Gracias y un saludo.

**Comment by DbNero16** [comment]
Buenas tardes,

Tal y cómo decías, parece que se produce un error del servidor al enviar la notificación síncrona.

![capturatpv](https://user-images.githubusercontent.com/22574693/39002743-7f9d9fa8-43f9-11e8-9097-6fdae823fb0b.PNG)

**Comment by DbNero16** [comment]
Buenas tardes,

Tal y cómo decías, parece que se produce un error del servidor al enviar la notificación síncrona.
![capturatpv](https://user-images.githubusercontent.com/22574693/39003476-3a5b0988-43fb-11e8-814e-93a054493411.PNG)
