### ISSUE TITLE
Integración en una APP

### ISSUE THREAD

**Issue by ormedo** [mbuenoferrer/RedsysTPV#3]
Buenos dias Miguel Angel.

¿Seria posible utilizar tu libreria para una aplicación movil sin necesidad de crear un Form?

Estoy trabajando con una aplicación en Xamarin y los SDKs nativos que me ha proporcionado Redsys no funcionan y no contestan a mis correos.

Un saludo.

Manuel Franco Giraldez

**Comment by mabuenox** [comment]
Hola @ormedo, lo cierto es que nunca he necesitado utilizar el sistema de Redsys en una app móvil, desconozco si utilizan la misma plataforma. Esta librería está pensada únicamente para web, enviando un formulario. Quizá puedas reaprovechar algunas de las funcionalidades internas para generar la firma, pero ya te digo que no conozco cómo funciona la plataforma para mobile.

Siento no poder ayudarte más, un saludo.

**Comment by ormedo** [comment]
Si sirve a alguien de ayuda. Utilizando tu librería cree un webview en Xamarin para consumir el pago y la verdad es funciona de maravilla.

**Comment by joananms** [comment]
> Si sirve a alguien de ayuda. Utilizando tu librería cree un webview en Xamarin para consumir el pago y la verdad es funciona de maravilla.

Buenas amigo! me podrías decir como lo hiciste porfa? lo necesito!! publicaste el proyecto en una webapp y lo llamabas desde el móvil?

Saludos,

**Comment by ormedo** [comment]
Con un Webview es como lo integre finalmente.

**Comment by joananms** [comment]
> Con un Webview es como lo integre finalmente.

A mi con un webview de xamarin.forms me funciona correctamente, pero hay un tipo de tarjeta que es la business que me redirige al propio banco para poner el código de seguridad y es aquí donde me problemas de cookies 
![image](https://user-images.githubusercontent.com/12891938/86455555-127d6680-bd21-11ea-9cc5-1d9734a2cf60.png)

He intentado heredar de un custom render del proyecto de android aceptando las cookies de terceros pero tampoco...

Lo que intentare hacer ahora es desde el proyecto compartido, embeber el webview nativo de android.webbkit https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/code

Saludos,

**Comment by joananms** [comment]
Si a alguien le interesa mi solución fue mover las pantallas del proyecto .net standard a un proyecto compartido para utilizar controles nativos de cada plataforma.
Saludos,!
