### ISSUE TITLE
Value cannot be null.

### ISSUE THREAD

**Issue by cs111** [mbuenoferrer/RedsysTPV#4]
When i success transaction to ok url..it gives me an error "Value cannot be null."
![redsys_error](https://cloud.githubusercontent.com/assets/3855874/24902632/0f2bb72e-1eab-11e7-9b1a-edaeb2689a79.PNG)

all 3 variables receive null values

**Comment by mabuenox** [comment]
Hi @cs111 

I think you are focus wrong your solution. The value of "Ds_Merchant_MerchantURL" is the url that Redsys will call asynchronously always when payment is finished (either is success or not). Note that this page never will be call or redirect from a browser; only the servers of Redsys will call it and persists the response status on their systems (usually take the HTTP code 200 or 500, and you could see on the Redsys private area).

I recommend you to have a deeper understanding of the steps on a payment operation:
1. The commerce post an html form with obfuscated data and an operation signature.
2. If request is correct, platform redirect user to the bank payment page.
3. User types his card number on a secure bank page
4. and the platform sends a background request (asynchronously) to a specific commerce url to notify operation results.
5. User is redirected to a ok/ko page of the commerce.

The screenshot you attach seems to be the page that Redsys call asynchronously on step 4, so you couldn't debug like you are doing. It's expected the values are null, the url parameters are send by Redsys platform, and seems like you are calling the page directly with a browser.

Note that if are you running your project on localhost, this page is unreachable for Redsys servers.

Remember that there is a fully functional sample project on https://github.com/mbuenoferrer/RedsysTPV/tree/master/src/RedsysTPV.WebSample.

**Comment by cs111** [comment]
hi @mbuenoferrer ,
thanks for your reply.
but problem is still not solved
i upload all your code here
http://redsys.cellpos.net    as same on github.
but there is no any log into this file
http://redsys.cellpos.net/log1.txt
i change file name from response controller.
so please help me why not log add into file?
