### ISSUE TITLE
Log not write to file in response controller

### ISSUE THREAD

**Issue by cs111** [mbuenoferrer/RedsysTPV#5]
hi ,
i upload all source of redsys tpv here
http://redsys.cellpos.net
but after success transaction there is no any log 
http://redsys.cellpos.net/log.txt

please help me

**Comment by mabuenox** [comment]
I'm pretty sure that you are passing wrong url in Ds_Merchant_UrlOK of the PaymentRequest. But it's hard to know without more details. 

Anyway, this seems to be a problem of implementation. I'm sorry but it's not an issue of the library itself, so I can't help you anymore. This library is working in several projects without problems, and I can't give free support for projects that use it.

You should review the Redsys documentation, and ask them for support. 

Best regards.
