### ISSUE TITLE
Where should I enter the order data in the database?

### ISSUE THREAD

**Issue by palanganero** [mbuenoferrer/RedsysTPV#8]
where I must enter the data in the database, in "Ds_Merchant_MerchantURL"
or in "Ds_Merchant_UrlOK"?

**Comment by mabuenox** [comment]
I'm not sure what you mean with "enter data in the database" but... Ds_Merchan_UrlOK is the place that you should put all your code with actions according with the result (update database, send email, etc). Ds_Merchant_MerchantURL is only informative.
